---
#
# install elastic stack
#
- hosts: elk
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python-simplejson
  roles:
   - { role: java }
   - { role: elasticsearch }
   - { role: logstash2 }
   - { role: kibana2 }