---
#
# set up the mail server
#
- hosts: mail
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python-simplejson
  roles:
   - { role: postfix }
   - { role: dovecot }
   - { role: postgresql }
   - { role: apache }
   - { role: squirrelmail }