---
#
# set up the payment server
#
- hosts: payments
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python-simplejson
  roles:
   - { role: mysql }
   - { role: apache }
   - { role: phpmyadmin }
   - { role: payment }