---
#
# set up the wazuh server
#
- hosts: wazuh
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python-simplejson
  roles:
   - { role: wazuh_server }
   - { role: filebeat2 }