---
#
# install mysql
#
- name: set the mysql root password
  debconf:
    name: mysql-server-5.7
    question: mysql-server/root_password
    value: 'root'
    vtype: string
- name: confirm the mysql root password
  debconf:
    name: mysql-server-5.7
    question: mysql-server/root_password_again
    value: 'root'
    vtype: string
- name: install mysql-server
  apt:
    name: mysql-server
    state: present
- name: configure mysql-server
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
- name: restart mysql
  service:
    name: mysql
    state: restarted