---
#
# playbook to set up the web app server
#
- name: set up web app
  hosts: webapp
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: copy and execute script
      script: webapp.sh
    # - name: copy apache config file for php
    #   copy: src=~/scripts/dir.conf dest=/etc/apache2/mods-enabled/dir.conf