---
#
# change password regularly
#
- name: change password on contractor
  hosts: contractor
  tasks: 
    - name: change password
      shell: python changePassword.py {{ new_password }}
- name: change password on web database
  hosts: web
  tasks: 
    - name: change password
      shell: php changePassword.php {{ new_password }}

