---
#
# install john the ripper
#
- name: update apt cache
  apt:
    update_cache: yes
- name: install make
  apt:
    name: make
    state: present
- name: install john-ripper
  raw: sudo apt install john
- name: copy cracking wordlist
  copy:
    src: ../src/password
    dest: /home/ubuntu/password
    owner: root
    group: root
    mode: 0777




# - name: copy database sql script
#   copy:
#     src: ../src/john-1.8.0.tar.xz
#     dest: /home/ubuntu/john-1.8.0.tar.xz
#     owner: root
#     group: root
#     mode: 0644
# - name: extract tar files
#   raw: tar -xf /home/ubuntu/john-1.8.0.tar.xz
# - name: compile source
#   command: make clean linux-x86-64
#   args:
#     chdir: /home/ubuntu/john-1.8.0/src/