---
#
# install john the ripper
#
- name: update apt cache
  apt:
    update_cache: yes
- name: install make
  apt:
    name: make
    state: present
- name: install gcc
  apt:
    name: gcc
    state: present
- name: copy database sql script
  copy:
    src: ../src/john-1.8.0.tar.xz
    dest: /home/ubuntu/john-1.8.0.tar.xz
    owner: root
    group: root
    mode: 0644
- name: extract tar files
  raw: tar -xf /home/ubuntu/john-1.8.0.tar.xz
- name: compile source
  command: make clean linux-x86-64
  args:
    chdir: /home/ubuntu/john-1.8.0/src/