---
#
# playbook to set up the mail server
#
- name: set up mail
  hosts: mail
  tasks:
    - name: copy and execute script
      script: mail.sh
    - name: copy postfix config file
      copy: src=~/scripts/main.cf dest=/etc/postfix/main.cf
