---
#
# install wazuh agent
#
- name: install curl
  apt:
    name: curl
    state: present
- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
- name: install lsb-release
  apt:
    name: lsb-release
    state: present
- name: install wazuh gpg key
  apt_key:
    url: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
    state: present
- name: add the wazuh repository
  apt_repository:
    repo: deb https://packages.wazuh.com/apt xenial main
- name: update apt cache again
  apt:
    update_cache: yes
- name: install wazuh agent
  apt:
    name: wazuh-agent
    state: present
- name: configure wazuh agent
  template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: root
    mode: 0644
- name: add wazuh client keys
  template:
    src: client.keys.j2
    dest: /var/ossec/etc/client.keys
    owner: root
    group: root
    mode: 0644
- name: incorporate authd password
  template:
    src: authd.pass.j2
    dest: /etc/authd.pass
    owner: root
    group: root
    mode: 0644
- name: restart wazuh agent
  raw: /var/ossec/bin/ossec-control restart
#- name: register with wazuh server
#  raw: /var/ossec/bin/agent-auth -m 10.0.0.12 -P "password"
