---
#
# set up the ftp server
#
- hosts: ftp
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python-simplejson
  roles:
   - { role: vsftpd }
   - { role: wazuh_agent_ftp }
   - { role: packetbeat }