---
#
# set up the payment server
#
- hosts: payments
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python-simplejson
    - name: update /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: '127.0.0.1 payments'
    - name: update /etc/hostname
      raw: echo "payments" > /etc/hostname
    - name: persist new hostname
      raw: hostname payments
  roles:
   - { role: mysql }
   - { role: apache }
   - { role: phpmyadmin }
   - { role: payment }
   - { role: wazuh_agent_payments }