---
#
# set up the wazuh server
#
- hosts: wazuh
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python-simplejson
    - name: update /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: '127.0.0.1 wazuh'
    - name: update /etc/hostname
      raw: echo "wazuh" > /etc/hostname
    - name: persist new hostname
      raw: hostname wazuh
    - name: change ubuntu password
      user:
        name: ubuntu
        update_password: always
        password: $6$kKb9TinGX$ACkjEConKRLRELB7llPSFjmkyRJRhQAMRS3Mw1iDRr55shl70EGVNvuYgnXcK9jLO3LRIgLZ04cyb2lrvOkaR1
  roles:
   - { role: wazuh_server }
   - { role: filebeat2 }