---
#
# set up the web server
#
- hosts: web
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python-simplejson
    - name: update /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: '127.0.0.1 web'
    - name: update /etc/hostname
      raw: echo "web" > /etc/hostname
    - name: persist new hostname
      raw: hostname web
    - name: change ubuntu password
      user:
        name: ubuntu
        update_password: always
        password: $6$kKb9TinGX$ACkjEConKRLRELB7llPSFjmkyRJRhQAMRS3Mw1iDRr55shl70EGVNvuYgnXcK9jLO3LRIgLZ04cyb2lrvOkaR1
    - name: create wheel group
      group:
        name: wheel
        state: present
    - name: add john user 
      user:
        name: john
        password: $6$wKcyu5nVPtgq$/TgaDTi/S5FfEyhT81rhX7ngKhJ0P5Pl.66RE91F0mivqPAJVyydWaOq9WvA2g52tLtTgTpzb8x6viUR78GLC1
        group: users
        groups: wheel
    - name: add www-data user 
      user:
        name: www-data
        group: users
        groups: wheel
    - name: allow wheel group passwordless sudo 
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    - name: add sudoers to wheel
      user:
        name: deployer
        groups: wheel
        append: yes
        state: present
        createhome: yes
  roles:
    - { role: zip }
    - { role: apache }
    - { role: php }
    - { role: mysql }
    - { role: web_app }
    - { role: wazuh_agent_web }
    - { role: packetbeat }
    - { role: metricbeat }
    - { role: filebeat }