---
#
# set up the web server
#
- hosts: webapp
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python-simplejson
  roles:
   - { role: apache }
   - { role: php }
   - { role: mysql }
   - { role: web_app }
   - { role: wazuh_agent_web }
   - { role: packetbeat }