---
#
# install java 8
#
- name: add java repository
  apt_repository:
    repo: ppa:webupd8team/java
- name: accept oracle license
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select
- name: saw oracle license
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: seen
- name: install java 8
  apt:
    name: oracle-java8-installer
    state: present
    update_cache: yes