---
#
# playbook to set up the ldap server
#
- name: set up ldap
  hosts: ldap
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python-simplejson
  tasks:
    - name: copy and execute script
      script: ldap.sh