---
#
# install point of sales firmware
#
- name: install python-mysqldb
  apt:
    name: python-mysqldb
    state: present
- name: start processing payments
  shell: nohup python /home/ubuntu/payment-server/pos_firmware.py >/dev/null 2>&1 &