---
#
# install packetbeat
#
- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
- name: add the elastic gpg key
  apt_key:
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present
- name: add the elastic repository
  apt_repository:
    repo: deb https://packages.elastic.co/beats/apt stable main
    state: present
- name: update apt cache
  apt:
    update_cache: yes
- name: install libpcap 
  apt:
    name: libpcap0.8
    state: present
- name: install packetbeat
  apt:
    name: packetbeat
    state: present
- name: configure packetbeat
  template:
    src: packetbeat.yml.j2
    dest: /etc/packetbeat/packetbeat.yml
    owner: root
    group: root
    mode: 0644
- name: enable and start packetbeat
  service:
    name: packetbeat
    enabled: yes
    state: started
