---
#
# install wazuh
#
- name: update apt cache
  apt:
    update_cache: yes
- name: install curl
  apt:
    name: curl
    state: present
- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
- name: install lsb-release
  apt:
    name: lsb-release
    state: present
- name: install wazuh gpg key
  apt_key:
    url: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
    state: present
- name: add the wazuh repository
  apt_repository:
    repo: deb https://packages.wazuh.com/apt xenial main
- name: update apt cache again
  apt:
    update_cache: yes
- name: install wazuh-manager
  apt:
    name: wazuh-manager
    state: present
- name: configure wazuh
  template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: root
    mode: 0644
- name: add the nodejs repository
  raw: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
- name: install nodejs
  apt:
    name: nodejs
    state: present
- name: install wazuh-api
  apt:
    name: wazuh-api
    state: present
- name: add wazuh client keys
  template:
    src: client.keys.j2
    dest: /var/ossec/etc/client.keys
    owner: root
    group: root
    mode: 0644
- name: set authd password
  template:
    src: authd.pass.j2
    dest: /var/ossec/etc/authd.pass
    owner: root
    group: root
    mode: 0644
#- name: create ssl certificate for authd
#  raw: openssl req -x509 -batch -nodes -days 365 -newkey rsa:2048 -keyout /var/ossec/etc/sslmanager.key -out /var/ossec/etc/sslmanager.cert
#- name: listen for wazuh agent registration
#  raw: /var/ossec/bin/ossec-authd -P >/dev/null 2>&1 &