---
#
# install fetchmail
#
- name: install fetchmail
  apt:
    name: fetchmail
    state: latest
- name: create fetchmail configuration file
  template:
    src: fetchmailrc.j2
    dest: /home/ubuntu/.fetchmailrc
    owner: ubuntu
    group: ubuntu
    mode: 0600
- name: create a forward directory to split files
  template:
    src: forward.j2
    dest: /home/ubuntu/.forward
    owner: ubuntu
    group: ubuntu
    mode: 0600